### ISSUE TITLE
Check if Command Winget Exists before giving option to download using winget

### ISSUE THREAD

**Issue by NotTahaAli** [NotTahaAli/NASM-Tools#3]
## The Problem
- Currently the program still gives a "Install XYZ with Winget" option, even if client machine does not have winget

## Solution
- Use the command-exists module to check if winget command exists
- If it does not exist, do not show the option
- If there is only one option, do not show any options and default to that option

## Lines to Work on
[const choice = await vscode.window.showInformationMessage('NASM is not installed.', 'Install NASM Using Winget', 'Disable Extension');](https://github.com/NotTahaAli/NASM-Tools/blob/afcf820526d4dec387cd612cf16d11fb171be424/src/commands/enable.ts#L22)
[const choice = await vscode.window.showInformationMessage('DOSBOX or DOSBOX-X is not installed.', 'Install DOSBOX-X Using Winget', 'Disable Extension');](https://github.com/NotTahaAli/NASM-Tools/blob/afcf820526d4dec387cd612cf16d11fb171be424/src/commands/enable.ts#L57)

**Comment by iMuhammadWali** [comment]
I will do it.
