### ISSUE TITLE
Add Linux Package Manager Support

### ISSUE THREAD

**Issue by NotTahaAli** [NotTahaAli/NASM-Tools#4]
## Problem
- Currently the Extension only supports winget

## Solution
- Dynamically Check Which Linux Package Manager is Installed and Give Install option accordingly (Using command-exists)

## Lines to Work on
- [const choices = [];](https://github.com/NotTahaAli/NASM-Tools/blob/d9f8cb78a080a120960f0586d988d6de63102bb3/src/commands/enable.ts#L22)
- [const choices = [];](https://github.com/NotTahaAli/NASM-Tools/blob/d9f8cb78a080a120960f0586d988d6de63102bb3/src/commands/enable.ts#L62)

**Comment by lw-lonewolf** [comment]
I'll get this done.

**Comment by lw-lonewolf** [comment]
@NotTahaAli Please test [this branch](https://github.com/lw-lonewolf/NASM-Tools/tree/linux_pkg_mgrs_support) for Windows and let me know if further changes are required.

**Comment by NotTahaAli** [comment]
- Mismatch in Choices
- [if (choice === 'Install NASM Using Winget') {](https://github.com/lw-lonewolf/NASM-Tools/blob/77050e0c767f827e032dbb03cab853f9394a2825/src/commands/enable.ts#L39)
- [const package_managers = ['winget','pacman', 'apt', 'yum', 'dnf', 'brew'];](https://github.com/lw-lonewolf/NASM-Tools/blob/77050e0c767f827e032dbb03cab853f9394a2825/src/commands/enable.ts#L24)
- options contain Install NASM Using winget, while trying to look for Install NASM Using Winget.

**Comment by NotTahaAli** [comment]
- Please use commandExists instead of file check to accommodate various install directories as Linux package managers automatically add to default path
- This can be found on many lines of enable.ts such as
  - [if(existsSync('/usr/bin/nasm')){](https://github.com/lw-lonewolf/NASM-Tools/blob/77050e0c767f827e032dbb03cab853f9394a2825/src/commands/enable.ts#L103)
  - [if(existsSync('/usr/bin/nasm')){](https://github.com/lw-lonewolf/NASM-Tools/blob/77050e0c767f827e032dbb03cab853f9394a2825/src/commands/enable.ts#L122)
  - And Others
